config/routes.rb
Rails.application.routes.draw do
	devise_for :users

	root to: "outer_pages#index"
	
	resources :orgs
end

app/models/org.rb
# == Schema Information
#
# Table name: orgs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Org < ActiveRecord::Base
	has_many :user_org_links
	has_many :users, through: :user_org_links

	def add_user(user, role)
		user_org_links.create(user_id: user.id, role: role)
	end

	def has_user?(user)
		user_org_links.where(user_id: user.id).any?
	end

	def remove_user(user)
		link = user_org_links.find_by(user_id: user.id)
		raise "Org does not have user" if link.nil?
		link.destroy
	end

	validates :name, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  first_name             :string(255)
#  last_name              :string(255)
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
		:recoverable, :rememberable, :trackable, :validatable

	has_many :user_org_links
	has_many :orgs, through: :user_org_links

	validates :first_name, presence: true
	validates :last_name, presence: true
end

app/models/user_org_link.rb
# == Schema Information
#
# Table name: user_org_links
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  org_id     :integer
#  role       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class UserOrgLink < ActiveRecord::Base
	belongs_to :user
	belongs_to :org

	validates :user_id, presence: true
	validates :org_id, presence: true
	validates :role, presence: true

	ADMIN = "admin"
	OWNER = "owner"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include ParametersManager

	protect_from_forgery with: :exception
	before_action :configure_permitted_parameters, if: :devise_controller?

	protected

		def configure_permitted_parameters
			devise_parameter_sanitizer.for(:sign_up) << :first_name << :last_name
		end

end

app/controllers/orgs_controller.rb
class OrgsController < ApplicationController
	before_action :authenticate_user!

	def show
		@org = Org.find(params[:id])
		render "orgs/show"
	end

	def new
		render "orgs/new"
	end

	def create
		@org = Org.new(strong_org_params)
		if @org.save
			@org.add_user(current_user, UserOrgLink::OWNER)
			render json: { success: true, org: @org }
		else
			render json: { success: false, errors: @org.errors.messages }
		end
	end
end

app/controllers/outer_pages_controller.rb
class OuterPagesController < ApplicationController
	def index
		render "outer_pages/index"
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Title</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<% if user_signed_in? %>
			<%= render "layouts/nav/inner" %>
		<% else %>
			<%= render "layouts/nav/outer" %>
		<% end %>
		<div id="mainContent">
			<%= yield %>
		</div>
	</body>
</html>

app/views/layouts/nav/_inner.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Brand", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="main-navbar">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
				<li class="dropdown">

					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
						Organizations <span class="caret"></span>
					</a>
					<ul class="dropdown-menu" role="menu">
						<% if current_user.orgs.any? %>
							<% current_user.orgs.each do |org| %>
								<li><%= link_to org.name, org_path(org) %></li>
							<% end %>
							<li class="divider"></li>
						<% end %>
						<li>
							<%= link_to "New Organization", new_org_path %>
						</li>
					</ul>
				</li>

				<li><a href="#">Link</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/nav/_outer.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-navbar">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<%= link_to "Brand", root_path, class: "navbar-brand" %>
		</div>

		<div class="collapse navbar-collapse" id="main-navbar">
			<ul class="nav navbar-nav">
				<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>

				<li><a href="#">Link</a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Log In", new_user_session_path %></li>
			</ul>
		</div>
	</div>
</nav>

app/views/orgs/new.html.erb
<h2 class="text-center">New Organization</h2>

<%= react_component "OrgForm" %>

app/views/orgs/show.html.erb
<h2><%= @org.name %></h2>

app/views/outer_pages/index.html.erb
<h1 class="text-center">Brand</h1>

<p class="text-center">
	<em>
		"In my next life I want to live my life backwards."<br /> - Woody Allen
	</em>
</p>

<div class="text-center">
	<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-default" %>
</p>